export enum FieldType {
  simpleText = "SIMPLE_TEXT",
  longText = "LONG_TEXT",
  email = "EMAIL",
  PhoneNumber = "PHONE_NUMBER",
  checkBox = "CHECK_BOX",
  date = "DATE",
  dateTime = "DATE_TIME",
  number = "NUMBER",
  url = "URL",
  color = "COLOR",
  rating = "RATING",
  image = "IMAGE",
  file = "FILE",
  singleSelect = "SINGLE_SELECT",
  multiSelect = "MULTI_SELECT",
  documentSelect = "DOCUMENT_SELECT",
  last = "LAST",
}
